### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by KunathBJ** [msproteomicstools/msproteomicstools#104]
Hello,

I tried to install msproteomicstools in the context of FragPipe (MSFragger) that requires  msproteomicstools for the spectral library generation.
I'm on windows 10 and try to install msproteomicstools but I get a very basic but that I can't fix on my own.
Could you help me please? Here is the log of the installation:

`C:\Program Files\Python37\Scripts>pip.exe install msproteomicstools
Collecting msproteomicstools
  Using cached https://files.pythonhosted.org/packages/5d/53/ae715b4dec1e9baa087c7a484c33a9b6d619a0b9e7db9c9802a4bc807b6b/msproteomicstools-0.8.0.tar.gz
Requirement already satisfied: numpy in c:\program files\python37\lib\site-packages (from msproteomicstools) (1.16.2)
Collecting scipy (from msproteomicstools)
  Downloading https://files.pythonhosted.org/packages/58/f0/d00c0e01e077da883f030af3ff5ce653a0e9e4786f83faa89a6e18c98612/scipy-1.2.1-cp37-cp37m-win_amd64.whl (30.0MB)
    100% |████████████████████████████████| 30.0MB 936kB/s
Collecting cluster==1.2.2 (from msproteomicstools)
  Using cached https://files.pythonhosted.org/packages/cd/25/f1c91218016ce8d8f78ed6544f318c7c49df65a030464cc27b148831e2cd/cluster-1.2.2.tar.gz
Collecting pyteomics>=2.4.0 (from msproteomicstools)
  Using cached https://files.pythonhosted.org/packages/0d/c8/d17a580f6e99e4d686f73c7cae28fc5afb344ef05f5e48eaf2021e32a034/pyteomics-4.0.1-py2.py3-none-any.whl
Collecting statsmodels>=0.6.0 (from msproteomicstools)
  Downloading https://files.pythonhosted.org/packages/41/a9/a89fced784543d565b49f5f1e52d6b90ad53f498eae85e09d16e1c3581a8/statsmodels-0.9.0-cp37-none-win_amd64.whl (7.0MB)
    100% |████████████████████████████████| 7.0MB 3.3MB/s
Collecting xlsxwriter>=0.5.3 (from msproteomicstools)
  Using cached https://files.pythonhosted.org/packages/6e/57/8c0fe0f6d8a4c57c32528c8b1b31c0daba53af33cd3afedf3fcb0971c75a/XlsxWriter-1.1.5-py2.py3-none-any.whl
Collecting scikits.datasmooth (from msproteomicstools)
  Using cached https://files.pythonhosted.org/packages/09/45/e0d0cde5ff9e0abe52697e6a2dc403000710540e727db382b72cbf498197/scikits.datasmooth-0.61.tar.gz
Collecting pymzml==0.7.5 (from msproteomicstools)
  Using cached https://files.pythonhosted.org/packages/dd/1f/081559a56d29cbfeaa345f27b4a706a648056788eb85be893da5f463884a/pymzml-0.7.5.zip
Collecting lxml (from msproteomicstools)
  Downloading https://files.pythonhosted.org/packages/be/b9/d05cd1680537aa39d8f0546871a4e56d82a5fdc97ac4006c37076a94915a/lxml-4.3.2-cp37-cp37m-win_amd64.whl (3.6MB)
    100% |████████████████████████████████| 3.6MB 6.6MB/s
Collecting configobj (from msproteomicstools)
  Using cached https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
Requirement already satisfied: biopython in c:\program files\python37\lib\site-packages (from msproteomicstools) (1.73)
Collecting xlwt (from msproteomicstools)
  Using cached https://files.pythonhosted.org/packages/44/48/def306413b25c3d01753603b1a222a011b8621aed27cd7f89cbc27e6b0f4/xlwt-1.3.0-py2.py3-none-any.whl
Requirement already satisfied: pandas in c:\program files\python37\lib\site-packages (from statsmodels>=0.6.0->msproteomicstools) (0.24.1)
Collecting patsy (from statsmodels>=0.6.0->msproteomicstools)
  Using cached https://files.pythonhosted.org/packages/ea/0c/5f61f1a3d4385d6bf83b83ea495068857ff8dfb89e74824c6e9eb63286d8/patsy-0.5.1-py2.py3-none-any.whl
Requirement already satisfied: six in c:\program files\python37\lib\site-packages (from configobj->msproteomicstools) (1.12.0)
Requirement already satisfied: pytz>=2011k in c:\program files\python37\lib\site-packages (from pandas->statsmodels>=0.6.0->msproteomicstools) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\program files\python37\lib\site-packages (from pandas->statsmodels>=0.6.0->msproteomicstools) (2.8.0)
Installing collected packages: scipy, cluster, pyteomics, patsy, statsmodels, xlsxwriter, scikits.datasmooth, pymzml, lxml, configobj, xlwt, msproteomicstools
  Running setup.py install for cluster ... done
  Running setup.py install for scikits.datasmooth ... done
Could not install packages due to an EnvironmentError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"c:'`

Thanks a lot for your help,

Ben

**Comment by hroest** [comment]
Hi @KunathBJ what was the problem here? It may be useful for others that have the same issue?

**Comment by KunathBJ** [comment]
Hey.

Sorry, I should have written it.
The issue was that Python was installed in place where there was a space in the path (Program Files). Moving it to a no space path made it work just fine :)

Ben
