### ISSUE TITLE
Please add more modifications

### ISSUE THREAD

**Issue by fcyu** [msproteomicstools/msproteomicstools#24]
The modifications available now is too few. When I translate a sequence to a peptide object, there are always an error like: 

This modification has not been recognized :  C[174]
Found in the following sequence :  LVGC[174]GNAYC[174]PNQK
The code used to interpret it was :  TPP

It like a nightmare.
Could you adding more modifications or privide a tsv file for import.

Thx

**Comment by mesontau** [comment]
You can add your own modifications by using the function Modifications.readModificationsFile. It reads a tsv formatted as follows:

modified-AA    TPP-nomenclature    Unimod-Accession    ProteinPilot-nomenclature    is_a_labeling    composition-dictionary
        S    S[167]    21    [Pho]    False    {'H' : 1,'O' : 3, 'P' : 1}

**Comment by hroest** [comment]
maybe we should extend our list of sensible default modifications  that we provide a bit ?

**Comment by mesontau** [comment]
I would probably do it by adding a default tsv file, so that default modifications would be transparent to the user (no need to search in the code)

**Comment by fcyu** [comment]
Hi guys,

I added some in my code. Use them if they are useful:

modifications_obj = Mod.Modifications()
modification_obj = Mod.Modification('C', 'C[330]', 105, '[Icl]', True, {'H': 17, 'C': 10, 'N': 3, 'O': 3})
modifications_obj.appendModification(modification_obj)
modification_obj = Mod.Modification('C', 'C[339]', 106, '[Ich]', True, {'H': 17, '13C': 1, 'C': 9, 'N': 3, 'O': 3})
modifications_obj.appendModification(modification_obj)
modification_obj = Mod.Modification('C', 'C[518]', 20, '[PEO]', False, {'H': 30, 'C': 18, 'N': 4, 'O': 5, 'S':1})
modifications_obj.appendModification(modification_obj)
modification_obj = Mod.Modification('C', 'C[174]', 24, '[Pro]', False, {'H': 5, 'C': 3, 'N': 1, 'O': 1})
modifications_obj.appendModification(modification_obj)
modification_obj = Mod.Modification('K', 'K[171]', 5, '[CRM]', False, {'H': 1, 'C': 1, 'N': 1, 'O': 1})
modifications_obj.appendModification(modification_obj)

**Comment by mesontau** [comment]
Modifications are now passed by a default file, which can be easily modified by users. fcyu, you may add the modifications you need there.

**Comment by fcyu** [comment]
Thanks a lot.
