### ISSUE TITLE
Explanation of non-Administrator Install

### ISSUE THREAD

**Issue by DarioS** [msproteomicstools/msproteomicstools#72]
I installed the software using the command

```
pip install -t /biostat/software/Python/lib/python2.7/site-packages/ msproteomicstools --install-option=--install-scripts=/biostat/software/Python/bin
```

and the result was

```
Successfully installed msproteomicstools numpy scipy cluster pyteomics statsmodels xlsxwriter scikits.datasmooth pymzml lxml configobj biopython xlwt six
```

but I can't run the software because the chauvenet function isn't found.

```
$ /biostat/software/Python/bin/feature_alignment.py --help
Traceback (most recent call last):
  File "feature_alignment.py", line 42, in <module>
    from msproteomicstoolslib.math.chauvenet import chauvenet
ImportError: No module named msproteomicstoolslib.math.chauvenet
```

I don't see the missing file anywhere in the software directory.

```
$ find /biostat/software/* -name \*chauvenet\*
$
```

There should be instructions in the README file explaining how to do a successful user install of msproteomicstools.

**Comment by grosenberger** [comment]
The best way to install msproteomicstools as a user is via ``virtualenv``. Alternatively, if you are setting the target directory of ``pip`` manually, you might need to export this ``PYTHONPATH`` as well in order for ``feature_alignment.py`` to find msproteomstoolslib: https://stackoverflow.com/a/19404371

**Comment by DarioS** [comment]
Thanks. I tried out `virtualenv` for the first time and it seems to be a painless way to do Python software installations.
