### ISSUE TITLE
mProphet File Contains Absolute Path to Lukas Hard Drive

### ISSUE THREAD

**Issue by DarioS** [msproteomicstools/msproteomicstools#77]
In the `analysis/mProphet/` directory, the code file `mProphet.R` contains a path to Lukas' hard drive. `t.options["bin_dir"] <- "C:\\Users\\lukas\\Documents\\BGS\\prog\\Perl\\biognosys\\libs\\r_libs"` This would terminate with an error for anyone other than Lukas. There are also a number of `# TODO` comments, so it's unclear if this code should be used by end-users of msproteomicstools at all.

**Comment by hroest** [comment]
you probably should use `mProphetRunner.sh` to run it.

it seems like these are some default options if no options are given. However, I agree that the R script is currently not maintained and superseded by pyProphet, maybe @grosenberger can comment on the reason whether we want keep that in there. But I agree we should replace that part with an error and abort with a clear error message: https://github.com/msproteomicstools/msproteomicstools/blob/master/analysis/mProphet/mProphet.R#L243

**Comment by grosenberger** [comment]
``mProphet.R`` is legacy code that we don't use or maintain anymore. I will make a pull request to remove it.
