### ISSUE TITLE
spectrast2tsv.py from Aebersold 2015 doesn't generate an output .csv or most of the programmed print messages

### ISSUE THREAD

**Issue by stshuken** [msproteomicstools/msproteomicstools#80]
![screenshot3_no-output](https://user-images.githubusercontent.com/15837789/31798414-5c87ce44-b4e8-11e7-9c3d-1a8e15f02ade.png)
Hello,

I'm a grad student following the Aebersold protocol on SWATH library building: https://www.nature.com/nprot/journal/v10/n3/full/nprot.2015.015.html
I'm on Step 37(B)(i) where the Anaconda script spectrast2rsv.py is run to extract the 6 most intense fragment ion peaks from each consensus spectrum to generate a SWATH library.

When I run the script with the recommended options, the script runs without any error messages, but doesn't produce any print messages after the intro (ending with "Output file name (default: appends _peakview.txt)"). The next print message is supposed to be "Labeling file :" just a few lines later, but that never appears.

"C:\TPPdata>python C:\ProgramData\Anaconda2\Scripts\spectrast2tsv.py -1 350,2000
-s b,y -x 1,2 -o 6 -n 6 -p 0.05 -d -e -w swaths.txt -k openswath -a SpecLib_cons
_openswath.csv SpecLib_cons.sptxt

spectrast2tsv.py
---------------
This script is used as filter from spectraST files to swath input files.

Usage:
python spectrast2tsv.py [options] spectrast_file(s)
-h                  Display this help
-d                  Remove duplicate masses from labeling
-e                  Use theoretical mass
-f    fasta_file    Fasta file to relate peptides to their proteins (this is opt
ional).
-g    mass_modifs   List of allowed fragment mass modifications. Useful for phos
phorylation and neutral losses. Example: -g -79.97,-97.98,-17.03,-18.01
-i    labeling_file File containing the amino acid isotopic labeling mass shifts
. If this option is used, heavy transitions will be generated.
-k    output_key    Select the output provided. Keys available: openswath, peakv
iew. Default: peakview
-l    mass_limits   Lower and upper mass limits of fragment ions. Example: -l 40
0,2000
-m    mods_file     File with the modifications delta mass
-n    int           Max number of reported ions per peptide/z. Default: 20
-o    int           Min number of reported ions per peptide/z. Default: 3
-p    float         Maximum error allowed at the annotation of a fragment ion. D
efault: 0.05
-q    int            Number of processors to use (only for isoforms!). Default:
1
-s    ion_series    List of ion series to be used. Example: -s y,b
-t    time-scale    Options: minutes, seconds. Default: seconds.
-u     unimod-code    Use this unimod code as a switching modification. Useful f
or phosphorylations. Example: -u 21
-v                  Verbose mode.
-w    swaths_file   File containing the swath ranges. This is used to remove tra
nsitions with Q3 falling in the swath mass range. (line breaks in windows/unix f
ormat)
-x    allowed_frg_z Fragment ion charge states allowed. Default: 1,2
-y    UIS-order     When using a switching modification, this determines the UIS
 order to be calculated. If -1 is set, all transitions for each isoform will be
reported. Default : 2
-a    outfile       Output file name (default: appends _peakview.txt)

C:\TPPdata>"

I'm not very knowledgeable with Python so I hope this is an easy fix; maybe the issue arises from the age of the script?

Thanks,
Steven

[spectrast2tsv.txt](https://github.com/msproteomicstools/msproteomicstools/files/1400282/spectrast2tsv.txt)

**Comment by grosenberger** [comment]
Hi Steven,

It seems that you are using the flag ``-1 350,2000`` instead of ``-l 350,2000``:

``python C:\ProgramData\Anaconda2\Scripts\spectrast2tsv.py -1 350,2000
-s b,y -x 1,2 -o 6 -n 6 -p 0.05 -d -e -w swaths.txt -k openswath -a SpecLib_cons
_openswath.csv SpecLib_cons.sptxt``

Could you please check whether that solves the problem?

Best regards,
George

**Comment by stshuken** [comment]
Hi George,

Well that is very embarrassing. The font used in the Nat Protocols paper made this look exactly like a 1 but in retrospect that makes zero sense! Thank you. Hope you enjoyed answering an easy one. The command works now!

Thanks again,
Steven

**Comment by mesontau** [comment]
Steven,

if it comforts you, by the time I wrote the spectrast2tsv script I felt I was using so many parameters that I would have not discarded to use numbers or symbols as parameters. 

Best regards,
Pedro.

**Comment by stshuken** [comment]
The great Pedro Navarro! Thanks, this does make me feel a bit better. :)
-Steven
