### ISSUE TITLE
TRIC alignment error

### ISSUE THREAD

**Issue by sjr24** [msproteomicstools/msproteomicstools#94]
Greetings,
I ran the following command on for feature_alignment.py

C:\Users\Shawn\Downloads\openswath_output_files.tar\results\pyprophet>C:\Anaconda\Scripts\feature_alignment.py --in yanliu_J130905_003_SW_with_dscore_filtered.csv yanliu_J130905_004_SW_with_dscore_filtered.csv yanliu_J130905_005_SW_with_dscore_filtered.csv --out aligned.csv --method LocalMST --realign_method lowess_cython --max_rt_diff 60 --mst:useRTCorrection True --mst:Stdev_multiplier 3.0 --target_fdr 0.01 --max_fdr_quality 0.05

The command terminal returned the following error

usage: feature_alignment.py [-h] --in INFILES [INFILES ...]
                            [--file_format FILE_FORMAT] --out OUTFILE
                            [--out_matrix MATRIX_OUTFILE]
                            [--out_ids IDS_OUTFILE] [--out_meta YAML_OUTFILE]
                            [--fdr_cutoff 0.01] [--max_fdr_quality -1]
                            [--max_rt_diff 30] [--iso_max_rt_diff 30]
                            [--frac_selected 0] [--method METHOD]
                            [--verbosity 0]
                            [--matrix_output_method MATRIX_OUTPUT_METHOD]
                            [--realign_method REALIGN_METHOD]
                            [--disable_isotopic_grouping]
                            [--use_dscore_filter] [--dscore_cutoff 1.96]
                            [--nr_high_conf_exp 1] [--readmethod minimal]
                            [--tmpdir TMPDIR] [--alignment_score 0.0001]
                            [--mst:useRTCorrection False]
                            [--mst:Stdev_multiplier -1.0]
                            [--mst:useLocalStdev False] [--target_fdr 0.01]
                            [--realign_runs] [--use_external_r]
feature_alignment.py: error: argument --in is required

The same error occurred on my own data and this data from the tutorial.  I tried a variety of commands, but kept getting the same error.  It seem like the input files are not being recognized.  Do you have any suggestions?

Thanks,
Shawn

**Comment by hroest** [comment]
> feature_alignment.py: error: argument --in is required

This seems to be the error, on which platform (Windows, OSX or Linux) did you run the command? Is it possible that you copied the command from somewhere and the `--in` was actually using a different character? can you make sure to replace the `--in` by typing it again yourself?

> C:\Users\Shawn\Downloads\openswath_output_files.tar\results\pyprophet>

are you inside a regular directory or a zipped / tar file?

**Comment by sjr24** [comment]
Hannes,
Thanks for the suggestion.  The command was run on a windows 10 pc.  I retyped the entire command but same error occurred.  The current feature alignment script look different than the version I was using so I downloaded the new script but got the same error.  Any other suggestions?  Could memory be an issue?  The csv filed are not that big.  The machine has a single dual quad core processor that ran openswath up to this point.

Thanks,
Shawn


________________________________

**Comment by hroest** [comment]
can you try and reduce the command to 

C:\Anaconda\Scripts\feature_alignment.py --in yanliu_J130905_003_SW_with_dscore_filtered.csv --out aligned.csv 

again, make sure you actually manually type the `--in` and the `--out` part (not copy it). The error message indicates that it did not find the correct command line parameters. Also I suggest to use an explicit path to Python, e.g. 

python.exe C:\Anaconda\Scripts\feature_alignment.py --in yanliu_J130905_003_SW_with_dscore_filtered.csv --out aligned.csv 

or replace `python.exe` with `/path/to/python/python.exe `

**Comment by sjr24** [comment]
Hannes,

I got it to work.  Calling  ‘python.exe C:\...\feature_alignment.py …..’.  Thanks for your help.

Shawn

**Comment by hroest** [comment]
great to hear!
